### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by sripgm** [desaiyang/deploy#1]
Hi,
Need bitnami & Postgres sql installation guide to install. Please send in email. 

Thanks.

**Comment by desaiyang** [comment]
- after fixing the dyncould.com please install core-1.zip.

file shared in gdrive.

https://drive.google.com/file/d/1hN0xqI8QJLAKlhHAQn-7nIeq1R_BI2Xc/view?usp=sharing

**Comment by desaiyang** [comment]
9/12 build complete.
