### ISSUE TITLE
9/15 - drop

### ISSUE THREAD

**Issue by desaiyang** [desaiyang/deploy#4]
1. core-zip staged in gdrive.

2. consists of webcode, db password change and bitnami folder path name change.

3. also add an account gdesaiyan@dyncould.com for aREC. This is for testing the instructor functionalities. 

Thanks,
Guna

**Comment by sripgm** [comment]
Action Taken:

1) Core-zip latest (9/15) deployed live
2) Added gdesaiyan@dyncould.com  and approved it.


Thanks,
SD

**Comment by desaiyang** [comment]
gdesaiyan@dyncould.com after register

![image](https://user-images.githubusercontent.com/60084078/93621191-d3de7a80-f9f8-11ea-90bf-a9978cbec6cf.png)

**Comment by desaiyang** [comment]
9/15 drop closed.

got access to aws/windows server yesterday.
postgresql password changed.
bitnami folder changed to 21-0.
updated dyncould_approved with these.
![image](https://user-images.githubusercontent.com/60084078/93670371-8e818200-fab8-11ea-90ec-e5765bc9f3a3.png)

drop tested.
